name: CI
on: [push]

jobs:
  # This workflow contains a single job called "build"
  SuperLinter:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo CI testing my python project!

      # Runs a set of commands using the runners shell
      - name: Super-Linter
        uses: github/super-linter@v4.9.4
  # This workflow contains a single job called "build"

  SpellCheck:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - uses: rojopolis/spellcheck-github-actions@0.24.0
        name: Spellcheck